project_id = "jemhwgcrocepusudmnpp"

[functions.ai-chat]
verify_jwt = false

[functions.web-search]
verify_jwt = false

[functions.terminal-session]
verify_jwt = false

[functions.browser-session]
verify_jwt = false