// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jemhwgcrocepusudmnpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbWh3Z2Nyb2NlcHVzdWRtbnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTU0NzYsImV4cCI6MjA3MjI5MTQ3Nn0.QjrUzFERhDqHCn2KGYuY62X_rThfawKGhsG2PB1n2xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});